### ISSUE TITLE
Investigate LoRa Module

### ISSUE THREAD

**Issue by tedski999** [tedski999/bangnet#2]
Before we can properly start this project, we need to first find out exactly what LoRa module we have and what its capabilities are. We're also going to need to learn how we should program the board with our own code and deploy it on battery power.

**Comment by tedski999** [comment]
LoRa32 V1.0 product page: https://www.lilygo.cc/products/lora32-v1-0?variant=42341146067125
SX1276 specifications: https://semtech.my.salesforce.com/sfc/p/#E0000000JelG/a/2R0000001Rbr/6EfVZUorrpoKFfvaF_Fkpgp5kzjiNyiAbqcpqh9qSjE

**Comment by cianmawhinney** [comment]
FYI: The LoRa module showed up as a serial device straight away, but to get the Espressif boards to show up in platformio I needed to install this driver: https://www.silabs.com/developers/usb-to-uart-bridge-vcp-drivers?tab=downloads

Just sharing in case anyone else needs to do the same and so I remember what I did
