### ISSUE TITLE
Basic Web App

### ISSUE THREAD

**Issue by tedski999** [tedski999/bangnet#8]
We need to get started on the web server that will provide both the camera feed and an API for the LoRa32 and ESP32 boards. Python seems to be the popular choice these days, probably using some framework you are familiar with. This app will be hosted on some cloud, talk to Cian Doyle on getting that working.

**Comment by Alamoalone** [comment]
I have written a script file, but I need some data to test whether the algorithm is correct, any good suggestions?

**Comment by tedski999** [comment]
Generate some testing data. Use Python to choose a random point as the source of the bang `b=(x,y)`, then pick a few other random points as the locations of nearby sensors `s=[(sx0,sy0), (sx1,sy1), ...]`. Then calculate the distances between the bang and each sensor `d0=math.sqrt((x-sx0)**2+(y-sy0)**2)` and the time it would take for the sound wave to reach it + some simulated inaccuracy `t=d/343+random.randrange(-10,10)`. Now you have a series of points and when they heard the bang. Your script needs to convert that back into the best possible guess for `(x,y)`.

**Comment by Alamoalone** [comment]
Already push to server
