### ISSUE TITLE
Updating Software

### ISSUE THREAD

**Issue by tedski999** [tedski999/bangnet#9]
How can new updates be distributed to boards securely? What mechanisms allow the boards to have their software rewritten remotely?

**Comment by tedski999** [comment]
Pushing this back a week (or two...). Overall approach seems to be holding two instances of the program in memory, then when updating, one of them gets overwritten before execution is swapped to it. However, I believe it would be impossible to apply delta encoded updates to such an approach. I am leaning towards instead having something like a "do_update" procedure which is always located at a known address and is never updated and when executed, delta updates can overwrite everything else in program memory.
https://en.m.wikipedia.org/wiki/Delta_encoding
https://www.chromium.org/developers/design-documents/software-updates-courgette/

**Comment by tedski999** [comment]
To validate updates came from us before applying them, I believe patches will need to be first written to an intermediate buffer before its PKC signature is checked against the previously shared public key.

**Comment by tedski999** [comment]
As CianM pointed out, https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/ota.html has been a good place to start, plus https://docs.espressif.com/projects/esp-idf/en/latest/esp32/security/secure-boot-v1.html#signed-app-verify. The esp_ota_ops.h API is flexible enough that I actually think delta updates over LoRa will be feasible (https://github.com/ESP32-Musings/esp32_compressed_delta_ota_update) as received delta bytes can be patched with the current firmware partition before being written to the new partition with esp_ota_write(). I look into it and try implement it for next meeting.

**Comment by Alamoalone** [comment]
Using python's library--detools to generate small patches to update software
